### ISSUE TITLE
potential typo in json table mapping: 

### ISSUE THREAD

**Issue by jeroenterheerdt** [kaareseras/adx_hacs#1]
```.create table ['raw'] ingestion json mapping 'ha_json_mapping' '[{"column":"entity_id","path":"$.entity_id"},{"column":"state","path":"$.state"},{"column":"attributes","path":"$.attributes"},{"column":"last_changed","path":"$.last_canced"},{"column":"last_updated","path":"$.last_updated"},{"column":"context","path":"$.context"}]'```

should be:
```.create table ['raw'] ingestion json mapping 'ha_json_mapping' '[{"column":"entity_id","path":"$.entity_id"},{"column":"state","path":"$.state"},{"column":"attributes","path":"$.attributes"},{"column":"last_changed","path":"$.last_changed"},{"column":"last_updated","path":"$.last_updated"},{"column":"context","path":"$.context"}]'```

**Comment by kaareseras** [comment]
Hi, Thank you very much :-)

I have updated the read.me and fixed the issue
