### ISSUE TITLE
"Failed to connect"

### ISSUE THREAD

**Issue by mike-wood-dywidag** [kaareseras/adx_hacs#3]
Hey! This will be incredible if I can get it to work. So thank you in advance.
I'm getting and error "Failed to connect" 
Home assistant logs show it as a 401.

```
Forbidden (403-Forbidden): { "error": { "code": "Forbidden", "message": "Caller is not authorized to perform this action", "@type": "Kusto.DataNode.Exceptions.UnauthorizedDatabaseAccessException", "@message": "Principal 'aadapp=REDACTED' is not authorized to read database 'haadx'"

This normally represents a permanent error, and retrying is unlikely to help. Error details: DataSource='http://127.0.0.70:25125/v2/rest/querystreaming', 
```

I have created the service principal, added it to ADX ingestors and viewers.
`.show database ['haadx'] principals` shows all fields for the added ingestor as follows:
 
```
"Role": Database haadx Ingestor,
"PrincipalType": AAD Application,
"PrincipalDisplayName": Application from AAD tenant **MyTenantId**,
"PrincipalObjectId": Application from AAD tenant **MyTenantId**,
"PrincipalFQN": Application from AAD tenant **MyTenantId**,
"Notes": Added as 'Application from AAD tenant **MyTenantId**,
"RoleAssignmentIdentifier": 76494d4a-d92d-4567-952a-87d79aa727a8
```

This is using queue client.

Thanks

**Comment by kaareseras** [comment]
Are you using the ADX free cluster?
Are you using the ingest-yourURL path?

**Comment by mike-wood-dywidag** [comment]
Yeah, ADX free and the full ingestion URL. (https://)

**Comment by mike-wood-dywidag** [comment]
Would I expect other roles other than the (default on creation) admin within
`.show database haadx principal roles`? E.g. ingestor / viewer?

**Comment by kaareseras** [comment]
use this command to verify that you pricipal has both viewer and writer access to the database

.show database haadx principals

**Comment by mike-wood-dywidag** [comment]
PICNIC (problem in chair, not in computer) 
I did do that initially and could see the ingestion record, but totally forgot about the reader. 
I had also looked around the code and saw the testConnection method uses a `| take 1` query to verify connectivity.

As soon as you said "principal has both viewer and writer" it clicked in my head. 
Thank for for being so prompt.

**Comment by kaareseras** [comment]
Glad to help :-) I hope you will be happy with the integration, and please ping me if you need anything or have suggestions
